// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace TestForEfPowerTools.Models;

public partial class Context : DbContext
{
    public Context(DbContextOptions<Context> options)
        : base(options)
    {
    }

    public virtual DbSet<Table1> Table1s { get; set; }

    public virtual DbSet<Table2> Table2s { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Table1>(entity =>
        {
            entity.ToTable("Table1");

            entity.Property(e => e.Id).ValueGeneratedNever();
        });

        modelBuilder.Entity<Table2>(entity =>
        {
            entity.ToTable("Table2");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Table2Name)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.Table1).WithMany(p => p.Table2s)
                .HasForeignKey(d => d.Table1Id)
                .HasConstraintName("FK_Table2_Table1");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}