// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TestForEfPowerTools.Models;

public partial class Table2
{
    public int Id { get; set; }

    public string Table2Name { get; set; }

    public int? Table1Id { get; set; }

    public DateTime? Date1 { get; set; }

    public virtual Table1 Table1 { get; set; }
}