// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TestForEfPowerTools.Models;

public partial class Table1
{
    public int Id { get; set; }

    public string Table1Name { get; set; }

    public DateOnly Date2 { get; set; }

    public virtual ICollection<Table2> Table2s { get; set; } = new List<Table2>();
}